git mv all.js handlers
git mv block.js handlers
git mv drawer.js handlers
git mv headline.js handlers
git mv link.js handlers
git mv list.js handlers
git mv table.js handlers
git mv text.js handlers
git mv timestamp.js handlers
